Adding support for file-based reads and externalized type dependencies
OpenCyphal/pydsdl pull request #103
Opened 2024-05-27 19:47 UTC by thirtytwobits

This is non-breaking change that adds a new public method:

read_files - a file-oriented entry point to the front end. This takes a list of target DSDL files allowing the user to maintain an explicit list instead of depending on globular filesystem discovery. Furthermore this method returns a set which is the transitive closure of types depended on by the target list of types. This allows consumers to track dependencies and compiler back ends to generate .d files and otherwise support incremental builds.

The new method may increase performance for systems with large pools of messages when generating code for a small sub-set as it only considers the target and dependencies of the target when parsing dsdl files.

2024-06-05 23:06 UTC, thirtytwobits commented
ping? Any chance I can get a review on this?

2024-06-06 15:23 UTC, pavel-kirienko commented
@thirtytwobits Sorry, I will do it today

2024-06-07 17:06 UTC, pavel-kirienko requested changes
to be continued

2024-06-07 21:43 UTC, pavel-kirienko requested changes
Please see the comments to https://github.com/OpenCyphal/pydsdl/pull/101.

Suppose I invoke `read_files` with a root namespace `foo` and a DSDL definition named `foo.foo.Bar.1.0`; is this going to work? What about `foo.baz.foo.Bar.1.0`?

2024-06-07 21:43 UTC, pavel-kirienko commented on pydsdl/_namespace.py
> +        standard namespace.
The param docs are out of sync with the function.

2024-06-07 21:43 UTC, pavel-kirienko commented on pydsdl/_namespace.py
> +class DsdlPathInferenceError(_error.InvalidDefinitionError):
Do you think we need `InvalidUsageError`?

2024-06-07 21:43 UTC, pavel-kirienko commented on test/test_public_types.py
Let us please postpone this (and the corresponding fixture in `conftest.py`, and also the related change to `setup.cfg`) until a follow-up PR, which will also address #105

2024-06-07 21:43 UTC, pavel-kirienko commented on pydsdl/_dsdl.py
> +)
Why lambda when you could use a well-typed function?

```suggestion
def get_definition_ordering_rank(d: DSDLFile | CompositeType) -> tuple[str, int, int]:
    return d.full_name, -d.version.major, -d.version.minor
```

2024-06-07 21:43 UTC, pavel-kirienko commented on pydsdl/_dsdl.py
> +SortedFileT = TypeVar("SortedFileT", DsdlFile, DsdlFileBuildable, CompositeType)
`DsdlFileBuildable` is redundant.

2024-06-07 21:43 UTC, pavel-kirienko commented on pydsdl/_dsdl.py
> +:param DsdlFile argument 1: The dependency of target_dsdl_file file the parser is about to parse.
Are you sure you don't want a dataclass for this? Otherwise it will be difficult to extent as you'd need to alter all occurrences.

2024-06-19 17:36 UTC, thirtytwobits commented on noxfile.py
> +        # we run mypy and pylint only on the oldest Python version to ensure maximum compatibility
As explained in the dev call last week, this would create a lot of noise in dealing with the deprecated 3.8 usages of things like `Optional` where 3.11 wants us to use `| None` etc. This way we ensure we are compatible with the LCD of our support matrix.

2024-06-19 18:10 UTC, pavel-kirienko commented on noxfile.py
> +        # we run mypy and pylint only on the oldest Python version to ensure maximum compatibility
I know. As I said, I am fine with updating the codebase manually to comply with 3.11. It will have to be done at some point anyway.

2024-06-19 22:14 UTC, thirtytwobits commented on noxfile.py
> +        # we run mypy and pylint only on the oldest Python version to ensure maximum compatibility
But then it won't be compatible with 3.8.

2024-06-19 22:22 UTC, pavel-kirienko commented
But there's a future import for that

On Thu, Jun 20, 2024, 01:14 Scott Dixon ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In noxfile.py
> <https://github.com/OpenCyphal/pydsdl/pull/103#discussion_r1646722260>:
>
> > -        "--strict",
> -        f"--config-file={ROOT_DIR / 'setup.cfg'}",
> -        "pydsdl",
> -        env={
> -            "MYPYPATH": str(THIRD_PARTY_DIR),
> -        },
> -    )
> -    session.run(
> -        "pylint",
> -        str(ROOT_DIR / "pydsdl"),
> -        env={
> -            "PYTHONPATH": str(THIRD_PARTY_DIR),
> -        },
> -    )
> +    if is_oldest_python(session):
> +        # we run mypy and pylint only on the oldest Python version to ensure maximum compatibility
>
> But then it won't be compatible with 3.8.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenCyphal/pydsdl/pull/103#discussion_r1646722260>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAZFIZAWRDF3TUYINF7ZS53ZIH7GDAVCNFSM6AAAAABILVRJOSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMRZGA4TCNZTGY>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-06-20 16:47 UTC, thirtytwobits commented on pydsdl/_dsdl_definition.py
> +            # the file is not under the same root path so we'll have to make an assumption that the
This functionality was moved out into `_infer_path_to_root`. I'll revert.

2024-06-20 17:00 UTC, thirtytwobits commented on pydsdl/_namespace.py
> +class DsdlPathInferenceError(_error.InvalidDefinitionError):
Sorry, what are you asking here?

2024-06-20 17:04 UTC, pavel-kirienko commented on pydsdl/_namespace.py
> +class DsdlPathInferenceError(_error.InvalidDefinitionError):
What I'm asking is: is it correct to define a path inference error as a special case of an invalid definition error, or does it belong to a different category of errors which are usage errors?

2024-06-20 17:39 UTC, thirtytwobits commented on pydsdl/_namespace.py
> +class DsdlPathInferenceError(_error.InvalidDefinitionError):
It is a special case.

2024-06-20 17:43 UTC, pavel-kirienko commented on pydsdl/_namespace.py
> +class DsdlPathInferenceError(_error.InvalidDefinitionError):
yeah, a special case of what?

![image](https://github.com/OpenCyphal/pydsdl/assets/3298404/9a5b0915-7360-4911-bb3d-706ebac6d3fe)

2024-06-20 17:51 UTC, thirtytwobits commented on pydsdl/_namespace.py
> +class DsdlPathInferenceError(_error.InvalidDefinitionError):
Inference is a heuristic that depends on the filesystem in use. As such, we should expect weird edge cases to arise when used in operating systems or build systems that we haven't previously tested on. It'll help us know that we are seeing this kind of issue if this is the error type in a defect report.

2024-06-20 19:29 UTC, pavel-kirienko commented on pydsdl/_namespace.py
> +class DsdlPathInferenceError(_error.InvalidDefinitionError):
>It'll help us know that we are seeing this kind of issue if this is the error type in a defect report.

This error type is for errors related to bad input files. I think in that case you may want to use `pydsdl.InternalError` instead. See the diagram here: https://pydsdl.readthedocs.io/en/stable/pages/pydsdl.html#exceptions

2024-06-20 20:15 UTC, thirtytwobits commented on pydsdl/_namespace.py
> +class DsdlPathInferenceError(_error.InvalidDefinitionError):
It's not that the files are bad it's that the paths given to, possibly correct, files are not in a form we can use to infer the namespace.

2024-06-20 21:29 UTC, thirtytwobits commented on pydsdl/_dsdl.py
> +:param DsdlFile argument 1: The dependency of target_dsdl_file file the parser is about to parse.
Yes! I did want that but your comment was that this was not "pythonic"? Can I use a class after all?

2024-06-20 21:42 UTC, thirtytwobits commented on pydsdl/_dsdl.py
> +SortedFileT = TypeVar("SortedFileT", DsdlFile, DsdlFileBuildable, CompositeType)
Mypy disagrees.

2024-06-20 22:29 UTC, thirtytwobits commented
Okay. Just the `DsdlPathInferenceError` comment is left.

2024-06-21 07:29 UTC, pavel-kirienko commented on pydsdl/_dsdl.py
> +:param DsdlFile argument 1: The dependency of target_dsdl_file file the parser is about to parse.
A dataclass, not a class; just pack the args:

```python
@dataclasses.dataclass(frozen=True)
class VisitorArgs:
    target_file: DsdlFile
    dependent_file: DsdlFileBuildable
```

2024-06-21 07:33 UTC, pavel-kirienko commented on pydsdl/_namespace.py
> +class DsdlPathInferenceError(_error.InvalidDefinitionError):
Okay, but which error type should it be: `InternalError` or `InvalidDefinitionError`?

2024-06-21 17:57 UTC, thirtytwobits commented on pydsdl/_dsdl.py
> +:param DsdlFile argument 1: The dependency of target_dsdl_file file the parser is about to parse.
The use of a visitor type is even more extensible. For example, my next change (which I hope goes _much_ quicker) is to extend the visitor as such:

```
class DefinitionVisitor(ABC):
    """
    A visitor that is notified about DSDL file resolution.
    """

    @abstractmethod
    def on_filter(self, dsdl_file: DsdlFile) -> bool:
        """
        Called by the library before it hands a DSDL file to the parser.
        :param dsdl_file: The DSDL file the library is about to parse.
        :return: True to parse the file, False to skip it.
        """
        raise NotImplementedError()

    @abstractmethod
    def on_definition(self, target_dsdl_file: DsdlFile, dependency_dsdl_file: DsdlFileBuildable) -> None:
        """
        Called by the parser after if finds a dependent type but before it parses a file in a lookup namespace.
        :param target_dsdl_file: The target DSDL file that has dependencies the parser is searching for.
        :param dependency_dsdl_file: The dependency of target_dsdl_file file the parser is about to parse.
        """
        raise NotImplementedError()
```

2024-06-21 18:09 UTC, thirtytwobits commented on pydsdl/_namespace.py
> +class DsdlPathInferenceError(_error.InvalidDefinitionError):
I'm not sure. It's really an input error but you wanted everything defined under `FrontendError`. I'm wondering if this is a subclass of `UndefinedDataTypeError` since that's what we through from `resolve_versioned_data_type` if a referenced type is not found. That seems to make a nice sentence, "The data type was undefined because we ere unable to infer the namespace from the lookup paths."

2024-06-24 22:53 UTC, pavel-kirienko commented on pydsdl/_dsdl.py
> +:param DsdlFile argument 1: The dependency of target_dsdl_file file the parser is about to parse.
Okay. I would design it in a more functional style with a callable that accepts several dataclass types, but it could be a mere matter of taste.

2024-06-24 22:53 UTC, pavel-kirienko commented on pydsdl/_namespace.py
> +class DsdlPathInferenceError(_error.InvalidDefinitionError):
That makes sense.

2024-06-24 23:03 UTC, pavel-kirienko commented on noxfile.py
> +        # we run mypy and pylint only on the oldest Python version to ensure maximum compatibility
I replied via email to this but I see that the response has not been added to this thread. There is `from __future__ import annotations` that enables support for the new syntax in v3.8. Please restore the MyPy check against all versions; I will introduce the sweeping updates necessary to fix the build.

2024-06-24 23:06 UTC, thirtytwobits commented on noxfile.py
> +        # we run mypy and pylint only on the oldest Python version to ensure maximum compatibility
so restored.

2024-06-25 09:22 UTC, pavel-kirienko commented
I tried pushing this but it says your `main` is protected; can you please either apply it or remove the main branch protection in your fork?

```diff
diff --git a/noxfile.py b/noxfile.py
index f9e73d2..61a409b 100644
--- a/noxfile.py
+++ b/noxfile.py
@@ -122,6 +122,3 @@ def docs(session):
 
 def is_latest_python(session) -> bool:
     return PYTHONS[-1] in session.run("python", "-V", silent=True)
-
-def is_oldest_python(session) -> bool:
-    return PYTHONS[0] in session.run("python", "-V", silent=True)
```

2024-06-25 17:27 UTC, thirtytwobits commented
> I tried pushing this but it says your `main` is protected; can you please either apply it or remove the main branch protection in your fork?
> 

This change is already in my PR.

2024-06-25 17:31 UTC, thirtytwobits commented
I believe all issues are addressed now?

2024-06-25 22:08 UTC, thirtytwobits commented
I fixed the CI build errors on my end. Everything is read to go.

2024-06-28 21:16 UTC, pavel-kirienko approved these changes

2024-06-28 21:17 UTC, merged