Fix for Issue #104
OpenCyphal/pydsdl pull request #107
Opened 2024-06-28 22:21 UTC by thirtytwobits

This changes our logic for detecting duplicate definitions on case-sensitive file-systems to only operate on files of interest and to fix this detection logic per issue #104.

If globular searches find duplicates we do not waste time detecting this until/unless these duplicates are actually considered when parsing target definitions.

2024-06-29 11:29 UTC, pavel-kirienko commented on pydsdl/_data_type_builder.py
> +                lambda d: d.full_name.lower() == full_name.lower() and d.version == version, self._lookup_definitions
This seems to make the search case-insensitive, why? In the Spec we state that identifiers are case-sensitive, but it is still considered a collision if identifiers differ by letter case only. Does this change allow the following:

```python
# Foo.1.0.dsdl
bar.1.0 bar  # Will "bar.1.0" name "Bar.1.0"?
@sealed
```

```python
# Bar.1.0.dsdl
@sealed
```

If yes, then it seems to be a problem.

2024-07-02 16:54 UTC, thirtytwobits commented on pydsdl/_data_type_builder.py
> +                lambda d: d.full_name.lower() == full_name.lower() and d.version == version, self._lookup_definitions
Since `Bar.1.0.dsdl` and `bar.1.0.dsdl` will both be accepted by this filter the later logic that requires only 1 result will raise the appropriate collision exception.

2024-07-02 17:47 UTC, pavel-kirienko commented on pydsdl/_data_type_builder.py
> +                lambda d: d.full_name.lower() == full_name.lower() and d.version == version, self._lookup_definitions
Okay but I'm not talking about collisions here, but rather the selectivity of the search. If I only have `Bar.1.0.dsdl` and I can name it `bar.1.0.dsdl`, we have a problem, right?

2024-07-02 18:16 UTC, thirtytwobits commented on pydsdl/_data_type_builder.py
> +                lambda d: d.full_name.lower() == full_name.lower() and d.version == version, self._lookup_definitions
You don't if only 1 dsdl file is found. If two are found then it is a collision caused either by case-sensitivity issues or by multiple paths to the same definition in different files. So selectivity doesn't matter since we never select one of multiple values returned from this filter.

2024-07-03 17:33 UTC, thirtytwobits commented on pydsdl/_data_type_builder.py
> +                lambda d: d.full_name.lower() == full_name.lower() and d.version == version, self._lookup_definitions
ping?

2024-07-08 22:32 UTC, pavel-kirienko commented on pydsdl/_data_type_builder.py
> +                lambda d: d.full_name.lower() == full_name.lower() and d.version == version, self._lookup_definitions
This behavior is not spec-conformant. I understand that collision is a non-issue and am in fact talking about a completely different issue here: if case doesn't match, the search should return nothing.

![image](https://github.com/OpenCyphal/pydsdl/assets/3298404/42d9eecf-f1c5-4343-910d-fc7b4f82e32c)

2024-07-08 22:36 UTC, pavel-kirienko requested changes
Can we please extend the test for issue 104 with another definition that contains the following field definition and ensure that it fails to parse:

```
a.b.thing.Thingtype.1.0 thing
```

2024-07-11 21:59 UTC, thirtytwobits commented
We good now?

2024-07-15 22:57 UTC, thirtytwobits commented
Ping? I have another PR parked behind this one too.

2024-07-16 09:29 UTC, pavel-kirienko approved these changes

2024-07-16 09:29 UTC, pavel-kirienko commented on pydsdl/_data_type_builder.py
> +                # This only happens if the file system is case-sensitive.
```suggestion
                # This only happens if the file system is case-insensitive.
```

2024-07-16 09:29 UTC, pavel-kirienko commented
Apologies for the delay, things pile up.

2024-07-16 18:00 UTC, merged