Fix for #82 PyDSDL allows same namespace name for lookup dir and root…
OpenCyphal/pydsdl pull request #88
Opened 2023-01-20 21:38 UTC by thirtytwobits

… namespace

Problem: Pydsdl does not allow using same root namespace names.

Solution: We made the check for root namespace name collisions optional.
Tests: Unit test, Manual test

2023-01-20 21:46 UTC, pavel-kirienko requested changes
This PR _has no style_, please run Black

2023-01-20 21:46 UTC, pavel-kirienko commented on pydsdl/_namespace.py
> +    # We will revert back to the official branch when this is fixed in the upstream.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/3298404/213810702-ca00691f-9da2-4ed9-9a25-65c55abaa922.png">

2023-01-20 21:48 UTC, thirtytwobits commented on pydsdl/_namespace.py
> +    # We will revert back to the official branch when this is fixed in the upstream.
whoops. look away!

2023-01-21 18:27 UTC, pavel-kirienko approved these changes
This is good to go despite the broken test with Python 3.6 on Windows, as it is clearly caused by a temporary issue either on the side of pip or PyPI. Feel free to merge.

2023-01-25 02:34 UTC, thirtytwobits commented
Merging. Will watch mainline to see if this is transient or not...

2023-01-25 02:34 UTC, merged