Added GH Actions workflow to replaced AppVeyor script
OpenCyphal/pydsdl pull request #98
Opened 2023-06-11 23:32 UTC by clyde-johnston

This PR addresses issue #87 to move the AppVeyor script to GH Actions.

**Issue:** 
The `_unittest_common_usage_errors` test fails on the Windows 2019 runner. It appears to be a problem with the test. Logs can be found [here](https://github.com/OpenCyphal/pydsdl/actions/runs/5237569083/jobs/9455833145). The runner has been commented out of the workflow file until this is resolved.

2023-06-20 15:38 UTC, pavel-kirienko requested changes

2023-06-20 15:38 UTC, pavel-kirienko commented on .github/workflows/make-release.yml
> +      - master
Let us please implement the same strategy as in the other projects: run on pull requests to `master` and also on push to any branch.

2023-06-20 15:38 UTC, pavel-kirienko commented on .github/workflows/make-release.yml
> +        os: [ubuntu-20.04]
```suggestion
        os: [ubuntu-latest]
```

why not?

2023-06-20 15:38 UTC, pavel-kirienko commented on .github/workflows/make-release.yml
> +          #  python: '3.10'
I think the failing test should be repairable by calling a `.resolve()` on both of the compared paths. This one should be uncommented so that we could verify the fix.

Also, ideally we should test all Pythons on Windows as well. And on macOS.

2023-06-20 15:38 UTC, pavel-kirienko commented on .github/workflows/make-release.yml
> +  # PyDSDL test
I don't want to nitpick unnecessarily but I just don't understand the point of comments that repeat the statement that immediately follows them. Maybe they should be removed?

2023-06-25 22:06 UTC, clyde-johnston commented on .github/workflows/make-release.yml
> +      - master
Ok, I have adjusted to push clause. It run the test on a push to any branch and pull request to `master`. It will run both the test and deployment on push to `master`. Note that these are not mutually exclusive. If you push to a branch with a pull request to `master` then you get two runs, one of which will be cancelled.

2023-06-25 22:07 UTC, clyde-johnston commented on .github/workflows/make-release.yml
> +        os: [ubuntu-20.04]
Python 3.6 does not run on the latest Ubuntu version 22.04. The AppVeyor script uses Ubuntu 20.04. If you don't need to test Python 3.6, then we can run the job on a new Ubuntu version runner.

2023-06-25 22:10 UTC, clyde-johnston commented on .github/workflows/make-release.yml
> +          #  python: '3.10'
I have uncommented this. You can view the error [here](https://github.com/OpenCyphal/pydsdl/actions/runs/5371931796/jobs/9745008256#step:7:657).

2023-06-25 22:10 UTC, clyde-johnston commented on .github/workflows/make-release.yml
> +  # PyDSDL test
I have removed these comments.

2023-06-25 22:14 UTC, clyde-johnston commented on .github/workflows/make-release.yml
> +      - master
Btw, we don't this implemented in the other projects. Let me know if I should change these too.

2023-08-13 14:00 UTC, pavel-kirienko commented
Same issue here, see PyCyphal

2023-08-19 15:20 UTC, merged